name: Deploy static content to Pages

on:
  push:
    branches:
      - add-support-ffb-wheel

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.x"
          check-latest: true

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      #
      # dfp
      #
      - name: Build Assets for dfp
        run: task assets wasm webpack TAGS="dfp"

      - name: Clone Assets for dfp
        run: |
          mkdir -p assets/dfp
          cp -a assets/content assets/dfp/
          cp -a assets/web assets/dfp/
          cp -a assets/preview assets/dfp/
          cp -a assets/index.html assets/dfp/
          cp -a assets/resources.yml assets/dfp/

      #
      # roller
      #
      - name: Build Assets for roller
        run: task assets wasm webpack TAGS="roller"

      - name: Clone Assets for roller
        run: |
          mkdir -p assets/roller
          cp -a assets/content assets/roller/
          cp -a assets/web assets/roller/
          cp -a assets/preview assets/roller/
          cp -a assets/index.html assets/roller/
          cp -a assets/resources.yml assets/roller/

      #
      # normal
      #
      - name: Build Assets for normal
        run: task assets wasm webpack TAGS=""

      - name: Clone Assets for normal
        run: |
          mkdir -p assets/normal
          cp -a assets/content assets/normal/
          cp -a assets/web assets/normal/
          cp -a assets/preview assets/normal/
          cp -a assets/index.html assets/normal/
          cp -a assets/resources.yml assets/normal/

      #
      # diy
      #
      - name: Build Assets for diy
        run: task assets wasm webpack TAGS="diy"

      #
      # GitHub Pages
      #
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./assets

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4