# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["add-support-ffb-wheel"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.25.0"
      - name: Setup Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
      - name: Build Assets fot dfp
        run: task assets wasm webpack
        env:
          TAGS: "dfp"
      - name: Clone for dfp
        run: mkdir ./assets/dfp && \
          cp -r ./assets/content ./assets/dfp/content && \
          cp -r ./assets/web ./assets/dfp/web && \
          cp -r ./assets/index.html ./assets/dfp/index.html && \
          cp -r ./assets/resources.yml ./assets/dfp/resources.yml
      - name: Build Assets fot diy
        run: task wasm
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./assets"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
